### ISSUE TITLE
Cannot run the project either way

### ISSUE THREAD

**Issue by emirotin** [prismicio/nextjs-blog#3]
Tried with Node v8 and v10

With `node-dev`:

```
❯ npm run node-dev

> nextjs-blog@0.0.3 node-dev /Users/emirotin/work/nextjs-blog
> nodemon server.js

[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
/Users/emirotin/work/nextjs-blog/prismic-configuration.js:1
import Prismic from 'prismic-javascript'
       ^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/emirotin/work/nextjs-blog/server.js:8:39)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
[nodemon] app crashed - waiting for file changes before starting...
```

with `dev`:

```
❯ npm run dev

> nextjs-blog@0.0.3 dev /Users/emirotin/work/nextjs-blog
> now dev

> UPDATE AVAILABLE The latest version of Now CLI is 15.8.7
> Run the `now update` command to update to the latest version
> Changelog: https://github.com/zeit/now-cli/releases/tag/15.8.7
> Now CLI 15.5.0 dev (beta) — https://zeit.co/feedback/dev
> Setting up 1 Builder
[@now/next] Downloading user files...

> Error! build_utils_1.getNodeVersion is not a function
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nextjs-blog@0.0.3 dev: `now dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nextjs-blog@0.0.3 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by levimykel** [comment]
Hi @emirotin, sorry for the delayed response on this. We modified this project to run fully in serverless mode and have removed the node.js server. So I'm closing this issue.
